server:
  command: "php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=8000"
  relay: pipes

http:
  address: 0.0.0.0:8000
  middleware: ["gzip"]
  uploads:
    forbid: [".php", ".exe", ".bat"]

rpc:
  listen: tcp://0.0.0.0:6001

jobs:
  num_pollers: 1
  pipelines:
    graphic_dictation:
      driver: amqp
      queue: generator.graphic_dictation
      exchange: ""
      prefetch: 8
      exclusive: false
      durable: true
    graphic_dictation_results:
      driver: amqp
      queue: generator.graphic_dictation.results
      exchange: ""
      prefetch: 8
      exclusive: false
      durable: true
  consume:
    - graphic_dictation
    - graphic_dictation_results
service:
  graphic_dictation_worker:
    command: "/var/www/bin/graphicdictation"
    process_num: 1
    restart_sec: 5
  graphic_dictation_results_consumer:
    command: "php artisan generator:graphic-dictation:consume-results"
    process_num: 1
    restart_sec: 5
